class Dijkstra:
    """
    A class that implements Dijkstra's algorithm to find the shortest path
    between two specific nodes in a graph.
    """

    def __init__(self, edges):
        """
        Initializes the Dijkstra solver with the graph's adjacency list.

        Args:
            edges (list of list): Adjacency list representing the graph. 
                                  Each index corresponds to a vertex, and each 
                                  entry is a list of pairs [destination, weight].
        """
        self.edges = edges
        self.number_of_vertices = len(edges)

    def _get_vertex_with_min_distance(self, distances, visited):
        """
        Helper method to find the vertex with the smallest known distance 
        that has not been visited.

        Args:
            distances (list): A list of the shortest known distances to each vertex.
            visited (set): A set of vertices that have already been visited.

        Returns:
            tuple: The index of the vertex with the smallest distance and its distance value.
        """
        current_min_distance = float("inf")
        vertex = -1

        for vertex_idx, distance in enumerate(distances):
            if vertex_idx in visited:
                continue

            if distance <= current_min_distance:
                vertex = vertex_idx
                current_min_distance = distance

        return vertex, current_min_distance

    def find_shortest_path(self, start, end):
        """
        Executes Dijkstra's algorithm to find the shortest path between a starting 
        node and a destination node. Terminates early once the destination is reached.

        Args:
            start (int): The starting node index.
            end (int): The destination node index.

        Returns:
            tuple: A tuple containing:
                - shortest_distance (float): The minimum distance from start to end. 
                                             Returns `inf` if the target is unreachable.
                - path (list): The sequence of nodes forming the path. 
                               Empty list if unreachable.
        """
        min_distances = [float("inf") for _ in range(self.number_of_vertices)]
        min_distances[start] = 0
        
        visited = set()
        previous_nodes = [None] * self.number_of_vertices

        while len(visited) != self.number_of_vertices:
            vertex, current_min_distance = self._get_vertex_with_min_distance(min_distances, visited)

            # Early exit: Stop if the remaining nodes are unreachable OR 
            # if we have just found the shortest path to our target destination.
            if current_min_distance == float("inf") or vertex == end:
                break

            visited.add(vertex)

            for edge in self.edges[vertex]:
                destination, distance_to_destination = edge

                if destination in visited:
                    continue

                new_path_distance = current_min_distance + distance_to_destination
                current_destination_distance = min_distances[destination]

                if new_path_distance < current_destination_distance:
                    min_distances[destination] = new_path_distance
                    previous_nodes[destination] = vertex

        path = self.reconstruct_path(previous_nodes, start, end)
        
        return min_distances[end], path

    @staticmethod
    def reconstruct_path(previous_nodes, start, end):
        """
        Reconstructs the path from the starting node to a target node.

        Args:
            previous_nodes (list): The predecessor list generated by the algorithm.
            start (int): The starting node index.
            end (int): The destination node index.

        Returns:
            list: The sequence of nodes forming the path. Empty list if unreachable.
        """
        path = []
        current_node = end

        while current_node is not None:
            path.append(current_node)
            current_node = previous_nodes[current_node]

        path.reverse()

        if not path or path[0] != start:
            return []

        return path
